version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=web_store
      - POSTGRES_USER=fcxmarquez
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5050:80
