version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=web_store
      - POSTGRES_USER=fcxmarquez
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
