version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=web_store
      - POSTGRES_USER=fcxmarquez
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=web_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql # this is the name of the service
    ports:
      - 8080:80
